spring:
  application:
    name: family-disk-scheduling
  datasource:
    url: jdbc:mysql://ip:port/schame?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: logback.xml
  level:
    com.jflove.mapper.*: debug
# 文件临时存放地,主要是一些大文件分片传输时,最后合并前临时存放
file:
  storage:
    path:
      temp: /home/family/app/temp