spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 171790872@qq.com
    password: dgurpkfvympxbjif
    frequency: 1 #每种类型的邮件发送频率控制,单位分钟
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://cdb-akyx5pzj.gz.tencentcdb.com:10048/family?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: family
    password: tanjun1994
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  application:
    name: family-disk-email
    qos-port: 3377
  protocol:
    name: dubbo
    port: 4477