spring:
  application:
    name: family-disk-netdisk
  datasource:
    url: jdbc:mysql://192.168.3.20:3306/family?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: family
    password: tanjun1994
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 7777
  protocol:
    name: dubbo
    port: 8877
logging:
  config: logback.xml