spring:
  datasource:
    url: jdbc:mysql://cdb-akyx5pzj.gz.tencentcdb.com:10048/family?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: family
    password: tanjun1994
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  application:
    name: family-disk-netdisk
    qos-port: 7777
  protocol:
    name: dubbo
    port: 8877