
server:
  port: 9999
logging:
  config: logback.xml
spring:
  security:
    ignored:
      files: #过滤掉的一些系统默认文件
        - .*
  application:
    name: family-disk-webdav
file:
  temp:
    # 文件上传时临时缓存目录
    path: /Users/tanjun/Downloads/
dubbo:
  consumer:
    timeout: 30000 # 超时时间
    retries: 0 # 不重试
  application:
    name: ${spring.application.name}
    qos-port: 3366
  protocol:
    name: dubbo
    port: 4466