
server:
  port: 9999
logging:
  config: logback.xml
spring:
  security:
    ignored:
      files: #过滤掉的一些系统默认文件
        - .*
  application:
    name: family-disk-webdav
dubbo:
  consumer:
    timeout: 10000 # 超时时间
    retries: 0 # 不重试
  application:
    name: ${spring.application.name}
    qos-port: 3366
  protocol:
    name: dubbo
    port: 4466