dubbo:
  consumer:
    timeout: 10000 # 超时时间
    retries: 0 # 不重试
  application:
    name: ${spring.application.name}
    qos-port: 5500
  protocol:
    name: dubbo
    port: 5511
spring:
  application:
    name: family-disk-notebook
  datasource:
    url: jdbc:mysql://49.232.164.11:13306/family?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: family
    password: tanjun1994
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  config: logback.xml
  level:
    com.jflove.*.mapper: debug